dataloader:
  batch_size: 2
  data_augmentation: false
  num_workers: 0
dataset:
  hdf5_file: datasets.hdf5
  root_dir: /kaggle/working
optimizer:
  learning_rate: 0.001
  lr_gamma: 0.1
  lr_step_milestones:
  - 30
  - 40
  momentum: 0.9
  weight_decay: 0.0001
system:
  cudnn_benchmark_enabled: false
  cudnn_deterministic: true
  seed: 42
trainer:
  device: cuda
  epoch_num: 10
  model_dir: /kaggle/working/modelscheckpoints
  model_save_best: true
  model_saving_frequency: 1
  normalization: false
  progress_bar: false
