system:
  seed: 42
  cudnn_benchmark_enabled: false
  cudnn_deterministic: true

dataset:
  root_dir: "/kaggle/working/"
  hdf5_file: "datasets.hdf5"

dataloader:
  batch_size: 250
  num_workers: 2
  data_augmentation: false

optimizer:
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  lr_step_milestones: [30, 40]
  lr_gamma: 0.1

trainer:
  model_dir: "checkpoints"
  model_save_best: true
  model_saving_frequency: 1
  device: "cpu"
  epoch_num: 50
  progress_bar: true
  normalization: false